"""auth

Revision ID: 03d24b1be473
Revises: 66e255f85d24
Create Date: 2026-01-04 23:20:54.959166
"""

from alembic import op
import sqlalchemy as sa


revision = '03d24b1be473'
down_revision = '66e255f85d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'native_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('user_profile', 'target_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'target_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('user_profile', 'native_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
