"""initial

Revision ID: 66e255f85d24
Revises: 
Create Date: 2026-01-04 22:13:59.448516
"""

from alembic import op
import sqlalchemy as sa


revision = '66e255f85d24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_lang', sa.String(length=2), nullable=False),
    sa.Column('target_lang', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpora_slug'), 'corpora', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma', 'lang', name='uq_words_lemma_lang')
    )
    op.create_table('corpus_word_stats',
    sa.Column('corpus_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('corpus_id', 'word_id')
    )
    op.create_index('ix_corpus_word_stats_corpus_count', 'corpus_word_stats', ['corpus_id', 'count'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('words_total', sa.Integer(), nullable=False),
    sa.Column('words_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('target_lang', sa.String(length=2), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'target_lang', 'translation', name='uq_translations_word_target')
    )
    op.create_index('ix_translations_word', 'translations', ['word_id'], unique=False)
    op.create_table('user_corpora',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('corpus_id', sa.BigInteger(), nullable=False),
    sa.Column('target_word_limit', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'corpus_id'),
    sa.UniqueConstraint('user_id', 'corpus_id', name='uq_user_corpora')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interface_lang', sa.String(length=2), nullable=False),
    sa.Column('native_lang', sa.String(length=2), nullable=False),
    sa.Column('target_lang', sa.String(length=2), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_new_words', sa.Integer(), nullable=False),
    sa.Column('daily_review_words', sa.Integer(), nullable=False),
    sa.Column('learn_batch_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_words',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('wrong_streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word_id')
    )
    op.create_index('ix_user_words_next_review', 'user_words', ['next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_words_next_review', table_name='user_words')
    op.drop_table('user_words')
    op.drop_table('user_settings')
    op.drop_table('user_profile')
    op.drop_table('user_corpora')
    op.drop_index('ix_translations_word', table_name='translations')
    op.drop_table('translations')
    op.drop_table('study_sessions')
    op.drop_table('review_events')
    op.drop_index('ix_corpus_word_stats_corpus_count', table_name='corpus_word_stats')
    op.drop_table('corpus_word_stats')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_corpora_slug'), table_name='corpora')
    op.drop_table('corpora')
    # ### end Alembic commands ###
